# Generated by Django 3.0.6 on 2020-07-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Starring',
            new_name='stars',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='screenwriter',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.CharField(default='', max_length=50, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='', max_length=50, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
